States = {
      'AL' => 'Alabama',
      'AK' => 'Alaska',
      'AS' => 'America Samoa',
      'AZ' => 'Arizona',
      'AR' => 'Arkansas',
      'CA' => 'California',
      'CO' => 'Colorado',
      'CT' => 'Connecticut',
      'DE' => 'Delaware',
      'DC' => 'District of Columbia',
      'FM' => 'Micronesia1',
      'FL' => 'Florida',
      'GA' => 'Georgia',
      'GU' => 'Guam',
      'HI' => 'Hawaii',
      'ID' => 'Idaho',
      'IL' => 'Illinois',
      'IN' => 'Indiana',
      'IA' => 'Iowa',
      'KS' => 'Kansas',
      'KY' => 'Kentucky',
      'LA' => 'Louisiana',
      'ME' => 'Maine',
      'MH' => 'Islands1',
      'MD' => 'Maryland',
      'MA' => 'Massachusetts',
      'MI' => 'Michigan',
      'MN' => 'Minnesota',
      'MS' => 'Mississippi',
      'MO' => 'Missouri',
      'MT' => 'Montana',
      'NE' => 'Nebraska',
      'NV' => 'Nevada',
      'NH' => 'New Hampshire',
      'NJ' => 'New Jersey',
      'NM' => 'New Mexico',
      'NY' => 'New York',
      'NC' => 'North Carolina',
      'ND' => 'North Dakota',
      'OH' => 'Ohio',
      'OK' => 'Oklahoma',
      'OR' => 'Oregon',
      'PW' => 'Palau',
      'PA' => 'Pennsylvania',
      'PR' => 'Puerto Rico',
      'RI' => 'Rhode Island',
      'SC' => 'South Carolina',
      'SD' => 'South Dakota',
      'TN' => 'Tennessee',
      'TX' => 'Texas',
      'UT' => 'Utah',
      'VT' => 'Vermont',
      'VI' => 'Virgin Island',
      'VA' => 'Virginia',
      'WA' => 'Washington',
      'WV' => 'West Virginia',
      'WI' => 'Wisconsin',
      'WY' => 'Wyoming',
      'AA' => 'Armed Forces (AA)',
      'AE' => 'Armed Forces (AE)',
      'AP' => 'Armed Forces (AP)',
      'MP' => 'Northern Mariana Islands'
    }

Sizes = [
  '2-Door',
  '4-Door',
  'SUV',
  'Pickup',
  'Van',
  'RV',
  'Trailer',
  'ATV',
  'Other'
]

Makes = {
  'Acura' => [
    '2.2CL',
    '2.3CL',
    '3.0CL',
    '3.2CL',
    'ILX',
    'Integra',
    'Legend',
    'MDX',
    'NSX',
    'RDX',
    '3.5RL',
    'RL',
    'RSX',
    'SLX',
    '2.5TL',
    '3.2TL',
    'TL',
    'TSX',
    'Vigor',
    'ZDX'
  ],
  'Audi' => [
    '100',
    '200',
    '4000',
    '5000',
    '80',
    '90',
    'A3',
    'A4',
    'A5',
    'A6',
    'A7',
    'A8',
    'Allroad Quattro',
    'Cabriolet',
    'Coupe',
    'Q3',
    'Q5',
    'Q7',
    'Quatro',
    'R8',
    'RS 4',
    'RS 5',
    'RS 6',
    'S4',
    'S5',
    'S6',
    'S7',
    'S8',
    'TT',
    'TT RS',
    'TTS',
    'V8 Quattro'
  ],
  'BMW' => [
    '128',
    '135',
    '318',
    '320',
    '323',
    '325',
    '328',
    '330',
    '335',
    '524',
    '525',
    '528',
    '530',
    '533',
    '535',
    '540',
    '545',
    '550',
    '633',
    '635',
    '640',
    '645',
    '650',
    '733',
    '735',
    '740',
    '745',
    '750',
    '760',
    '840',
    '850',
    'L7',
    '1 Series M',
    'M Coupe',
    'M Roadster',
    'M3',
    'M5',
    'M6',
    'X5 M',
    'X6 M',
    'Active Hybrid X6',
    'X1',
    'X3',
    'X5',
    'X6',
    'Z3',
    'Z4',
    'Z8'
  ],
  'Buick' => [
    'Century',
    'Electra',
    'Enclave',
    'LaCrosse',
    'Le Sabre',
    'Lucerne',
    'Park Avenue',
    'Rainier',
    'Reatta',
    'Regal',
    'Rendezvous',
    'Riviera',
    'Roadmaster',
    'Skyhawk',
    'Skylark',
    'Somerset',
    'Terraza',
    'Verano'
  ],
  'Cadillac' => [
    'Allante',
    'ATS',
    'Brougham',
    'Catera',
    'Cimarron',
    'CTS',
    'De Ville',
    'DTS',
    'Eldorado',
    'Escalade',
    'Escalade ESV',
    'Escalade EXT',
    'Fleetwood',
    'Seville',
    'SRX',
    'STS',
    'XLR',
    'XTS'
  ],
  'Chevrolet' => [
    'Astro',
    'Avalanche',
    'Aveo',
    'Aveo5',
    'Beretta',
    'Blazer',
    'Camaro',
    'Caprice',
    'Captiva Sport',
    'Cavalier',
    'Celebrity',
    'Chevette',
    'Citation',
    'CK 1500',
    'CK 2500',
    'CK 3500',
    'Cobalt',
    'Colorado',
    'Corsica',
    'Corvette',
    'Cruz',
    'El Camino',
    'Equinox',
    'Express Van',
    'G Van',
    'HHR',
    'Impala',
    'Kodiak 4500',
    'Lumina',
    'Lumina APV',
    'LUV',
    'Malibu',
    'Metro',
    'Monte Carlo',
    'Nova',
    'Prizm',
    'S10 Blazer',
    'S10 Pickup',
    'Silverado 1500',
    'Silverado 2500',
    'Silverado 3500',
    'Sonic',
    'Spark',
    'Spectrum',
    'Sprint',
    'SSR',
    'Suburban',
    'Tahoe',
    'Tracker',
    'Trailblazer',
    'Trailblazer EXT',
    'Traverse',
    'Venture',
    'Uplander',
    'Volt'
  ],
  'Chrysler' => [
    '200',
    '300',
    '300C',
    '300M',
    '300 SRT8',
    'Aspen',
    'Caravan',
    'Cirrus',
    'Concorde',
    'Conquest',
    'Cordoba',
    'Crossfire',
    'E Class',
    'Fifth Avenue',
    'Grand Voyager',
    'Imperial',
    'Intrepid',
    'Lazer',
    'LeBaron',
    'LHS',
    'Neon',
    'New Yorker',
    'Newport',
    'Pacifica',
    'Prowler',
    'PT Cruiser',
    'Sebring',
    'TC',
    'Town & Country',
    'Voyager'
  ],
  'Daewoo' => [
    'Lanos',
    'Leganza',
    'Nubira'
  ],
  'Datsun' => [
    '200SX',
    '210',
    '280ZX',
    '300ZX',
    '310',
    '510',
    '720',
    '810',
    'Maxima',
    'Pickup',
    'Pulsar',
    'Sentra',
    'Stanza'
  ],
  'Dodge' => [
    '400',
    '600',
    'Aries',
    'Avenger',
    'Caliber',
    'Caravan',
    'Challenger',
    'Charger',
    'Colt',
    'Conquest',
    'Dakota',
    'Dart',
    'Daytona',
    'Diplomat',
    'Durango',
    'Dynasty',
    'Grand Caravan',
    'Intrepid',
    'Journey',
    'Lancer',
    'Magnum',
    'Mirada',
    'Monaco',
    'Neon',
    'Neon SRT4',
    'Nitro',
    'Omni',
    'Raider',
    'Ram 1500',
    'Ram 2500',
    'Ram 3500',
    'Ram 4500',
    'Ram 50',
    'Ram SRT10',
    'Ram Van',
    'Ram Wagon',
    'Ramcharger',
    'Rampage',
    'Shadow',
    'Spirit',
    'Sprinter',
    'St Regis',
    'Stealth',
    'Stratus',
    'Viper'
  ],
  'Eagle' => [
    'Medallion',
    'Premier',
    'Summit',
    'Talon',
    'Vision'
  ],
  'FIAT' => [
    '2000 Spider',
    '500',
    'Bertone X19',
    'Brava',
    'Pininfarina Spider',
    'Strada',
    'X19'
  ],
  'Ford' => [
    'Aerostar',
    'Aspire',
    'Bronco',
    'Bronco II',
    'Club Wagon',
    'Contour',
    'Courier',
    'Crown Victoria',
    'E 150',
    'E 250',
    'E 350',
    'Econoline 150',
    'Econoline 250',
    'Econoline 350',
    'Edge',
    'Escape',
    'Escort',
    'Excursion',
    'EXP',
    'Expedition',
    'Expedition EL',
    'Explorer',
    'Explorer Sport Trac',
    'F100',
    'F150',
    'F250',
    'F350',
    'F450',
    'F550',
    'F650',
    'Fairmont',
    'Festiva',
    'Fiesta',
    'Five Hundred',
    'Flex',
    'Focus',
    'Freestar',
    'Freestyle',
    'Fusion',
    'Granada',
    'GT',
    'LTD',
    'Mustang',
    'Mustang GT', 
    'Probe',
    'Ranger',
    'Taurus',
    'Tempo',
    'Thunderbird',
    'Transit Connect',
    'Windstar'
  ],
  'Geo' => [
    'Metro',
    'Prizm',
    'Spectrum',
    'Storm',
    'Tracker'
  ],
  'GMC' => [
    'Acadia',
    'Caballero',
    'Canyon',
    'CK 1500',
    'CK 2500',
    'CK 3500',
    'Envoy',
    'Envoy XL',
    'Envoy XUV',
    'Jimmy',
    'Rally Wagon',
    'S15 Jimmy',
    'S15 Pickup',
    'Safari',
    'Savana',
    'Sierra 1500',
    'Sierra 2500',
    'Sierra 3500',
    'Sonoma',
    'Suburban',
    'Syclone',
    'Terrain',
    'Topkick 4500',
    'Typhoon',
    'Vandura',
    'Yukon',
    'Yukon XL'
  ],
  'Honda' => [
    'Accord',
    'Accord Crosstour',
    'Civic',
    'CR-V',
    'CR-Z',
    'CRX',
    'Crosstour',
    'Del Sol',
    'Element',
    'Fit',
    'Insight',
    'Odyssey',
    'Passport',
    'Pilot',
    'Prelude',
    'Ridgeline',
    'S2000'
  ],
  'HUMMER' => [
    'H1',
    'H2',
    'H3',
    'H3T'
  ],
  'Hyundai' => [
    'Accent',
    'Azera',
    'Elantra',
    'Elantra Coupe',
    'Elantra Touring',
    'Entourage',
    'Equus',
    'Excel',
    'Genesis',
    'Genesis Coupe',
    'Santa Fe',
    'Scoupe',
    'Sonata',
    'Tiburon',
    'Tucson',
    'Veloster',
    'Veracruz',
    'XG300',
    'XG350'
  ],
  'Infinity' => [
    'EX35',
    'FX35',
    'FX45',
    'FX50',
    'G20',
    'G25',
    'G35',
    'G37',
    'I30',
    'I35',
    'J30',
    'JX35',
    'M30',
    'M35',
    'M35H',
    'M37',
    'M45',
    'M56',
    'Q45',
    'QX4',
    'QX56'
  ],
  'Isuzu' => [
    'Amigo',
    'Ascender',
    'Axiom',
    'Hombre',
    'I-280',
    'I-290',
    'I-350',
    'I-370',
    'I-Mark',
    'Impulse',
    'Oasis',
    'Pickup',
    'Rodeo',
    'Stylus',
    'Trooper',
    'Trooper II',
    'VehiCROSS'
  ],
  'Jaguar' => [
    'S Type',
    'X Type',
    'XF',
    'XJ12',
    'XJ6',
    'XJR',
    'XJS',
    'XJ',
    'XJ8',
    'XJ8 L',
    'XJ Sport',
    'XK8',
    'XK',
    'XKR'
  ],
  'Jeep' => [
    'Cherokee',
    'CJ',
    'Comanche',
    'Commander',
    'Compass',
    'Grand Cherokee',
    'Grand Wagoneer',
    'Liberty',
    'Patriot',
    'Pickup',
    'Scrambler',
    'Wagoneer',
    'Wrangler'
  ],
  'Kia' => [
    'Amanti',
    'Borrego',
    'Forte',
    'Forte Koupe',
    'Optima',
    'Rio',
    'Rio5',
    'Rondo',
    'Sedona',
    'Sephia',
    'Sorento',
    'Soul',
    'Spectra',
    'Spectra5',
    'Sportage'
  ],
  'Land Rover' => [
    'Defender',
    'Discovery',
    'Freelander',
    'LR2',
    'LR3',
    'LR4',
    'Range Rover',
    'Range Rover Evoque',
    'Range Rover Sport'
  ],
  'Lexus' => [
    'CT200h',
    'ES250',
    'ES300',
    'ES330',
    'ES350',
    'GS300',
    'GS350',
    'GS400',
    'GS430',
    'GS450h',
    'GS460',
    'GX460',
    'GX470',
    'HS250h',
    'IS250',
    'IS250C',
    'IS350',
    'IS350C',
    'IS F',
    'LFA',
    'LS400',
    'LS430',
    'LS460',
    'LS600h',
    'LX450',
    'LX470',
    'LX570',
    'RX300',
    'RX330',
    'RX350',
    'RX400h',
    'RX450h',
    'SC300',
    'SC400',
    'SC430'
  ],
  'Lincoln' => [
    'Aviator',
    'Blackwood',
    'Continental',
    'LS',
    'Mark LT',
    'Mark VI',
    'Mark VII',
    'Mark VIII',
    'MKS',
    'MKT',
    'MKX',
    'MKZ',
    'Navigator',
    'Navigator L',
    'Town Car',
    'Zephyr'
  ],
  'Lotus' => [
    'Elan',
    'Elise',
    'Esprit',
    'Evora',
    'Exige'
  ],
  'Mazda' => [
    '323',
    '626',
    '929',
    'B Series Pickup',
    'CX-5',
    'CX-7',
    'CX-9',
    'GLC',
    'Mazda2',
    'Mazda3',
    'Mazda5',
    'Mazda6',
    'MazdaSpeed3',
    'MazdaSpeed6',
    'Miata MX-5',
    'Millenia',
    'MPV',
    'MX-3',
    'MX-6',
    'Navajo',
    'Protege',
    'Protege5',
    'RX-7',
    'RX-8',
    'Tribute'
  ],
  'Mercedes-Benz' => [
    '190D',
    '190E',
    '240D',
    '260E',
    '280CE',
    '280E',
    '300CD',
    '300CE',
    '300D',
    '300E',
    '300SD',
    '300SDL',
    '300SE',
    '300SEL',
    '300SL',
    '300TD',
    '300TE',
    '350SD',
    '350SDL',
    '380SE',
    '380SEC',
    '380SEL',
    '380SL',
    '380SLC',
    '400E',
    '400SE',
    '400SEL',
    '420SEL',
    '500E',
    '500SEC',
    '500SEL',
    '500SL',
    '560SEC',
    '560SEL',
    '560SL',
    '600SEC',
    '600SEL',
    '600SL',
    'C220',
    'C230',
    'C240',
    'C250',
    'C280',
    'C300',
    'C320',
    '32 AMG',
    'C350',
    '36 AMG',
    '43 AMG',
    '55 AMG',
    '63 AMG',
    'CL500',
    'CL550',
    'CL55 AMG',
    'CL600',
    'CL63 AMG',
    'CL65 AMG',
    'CLK320',
    'CLK350',
    'CLK430',
    'CLK500',
    'CLK550',
    'CLK55 AMG',
    'CLK63 AMG',
    'CLS500',
    'CLS550',
    'CLS55 AMG',
    'CLS63 AMG',
    'E300',
    'E320',
    'E320 Bluetec',
    'E320 CDI',
    'E350',
    'E350 Bluetec',
    'E400 Hybrid',
    'E420',
    'E430',
    'E500',
    'E550',
    'E55 AMG',
    'E63 AMG',
    'G500',
    'G550',
    'G55 AMG',
    'GL320 Bluetec',
    'GL320 CDI',
    'GL350 Bluetec',
    'GL450',
    'GL550',
    'GLK350',
    'ML320',
    'ML320 Bluetec',
    'ML320 CDI',
    'ML350',
    'ML350 Bluetec',
    'ML430',
    'ML450',
    'ML500',
    'ML550',
    'ML55 AMG',
    'ML63 AMG',
    'R320 Bluetec',
    'R320 CDI',
    'R350',
    'R350 Bluetec',
    'R500',
    'R63 AMG',
    'S320',
    'S350',
    'S350 Bluetec',
    'S400 Hybrid',
    'S420',
    'S430',
    'S500',
    'S550',
    'S55 AMG',
    'S600',
    'S63 AMG',
    'S65 AMG',
    'SL320',
    'SL500',
    'SL550',
    'SL55 AMG',
    'SL600',
    'SL63 AMG',
    'SL65 AMG',
    'SLK230',
    'SLK250',
    'SLK280',
    'SLK300',
    'SLK320',
    'SLK32 AMG',
    'SLK350',
    'SLK55 AMG',
    'SLR',
    'SLS AMG',
    'Sprinter'
  ],
  'Mercury' => [
    'Capri',
    'Cougar',
    'Grand Marquis',
    'Lynx',
    'Marauder',
    'Mariner',
    'Marquis',
    'Milan',
    'Montego',
    'Monterey',
    'Mountaineer',
    'Mystique',
    'Sable',
    'Topaz',
    'Tracer',
    'Villager',
    'Zephyr'
  ],
  'MINI' => [
    'Cooper',
    'Cooper S',
    'Cooper Clubman',
    'Cooper S Clubman',
    'Cooper Countryman',
    'Cooper S Countryman',
    'Cooper Coupe',
    'Cooper S Coupe',
    'Cooper Roadster',
    'Cooper S Roadster'
  ],
  'Mitsubishi' => [
    '3000GT',
    '3000GT VR4',
    'Cordia',
    'Diamante',
    'Eclipse',
    'Endeavor',
    'Expo',
    'Galant',
    'I',
    'Lancer',
    'Lancer Evolution',
    'Mirage',
    'Montero',
    'Montero Sport',
    'Outlander',
    'Outlander Sport',
    'Pickup',
    'Precis',
    'Raider',
    'Sigma',
    'Starion',
    'Tredia'
  ],
  'Nissan' => [
    '200SX',
    '240SX',
    '300ZX',
    '350Z',
    '370Z',
    'Altima',
    'Armada',
    'Axxess',
    'Cube',
    'Frontier',
    'GT-R',
    'Juke',
    'Leaf',
    'Maxima',
    'Murano',
    'Murano CrossCabriolet',
    'NV',
    'NX',
    'Pathfinder',
    'Pickup',
    'Pulsar',
    'Quest',
    'Rogue',
    'Sentra',
    'Stanza',
    'Titan',
    'Van',
    'Versa',
    'Xterra'
  ],
  'Oldsmobile' => [
    '88',
    'Achieva',
    'Aurora',
    'Bravada',
    'Custom Cruiser',
    'Cutlass',
    'Cutlass Calais',
    'Cutlass Ciera',
    'Cutlass Supreme',
    'Firenza',
    'Intrigue',
    'Ninety-Eight',
    'Omega',
    'Regency',
    'Silhouette',
    'Tornado'
  ],
  'Plymouth' => [
    'Acclaim',
    'Arrow',
    'Breeze',
    'Caravelle',
    'Champ',
    'Colt',
    'Conquest',
    'Duster',
    'Gran Fury',
    'Grand Voyager',
    'Horizon',
    'Laser',
    'Neon',
    'Prowler',
    'Reliant',
    'Sapporo',
    'Scamp',
    'Sundance',
    'Trailduster',
    'Voyager'
  ],
  'Pontiac' => [
    '6000',
    'Aztec',
    'Bonneville',
    'Catalina',
    'Fiero',
    'Firebird',
    'G3',
    'G5',
    'G6',
    'G8',
    'Grand Am',
    'Grand Prix',
    'GTO',
    'J2000',
    'Le Mans',
    'Montana',
    'Parisienni',
    'Phoenix',
    'Safari',
    'Solstice',
    'Sunbird',
    'Sunfire',
    'T1000',
    'Torrent',
    'Trans Sport',
    'Vibe'
  ],
  'Porsche' => [
    '911',
    '924',
    '928',
    '944',
    '968',
    'Boxter',
    'Carrera GT',
    'Cayenne',
    'Cayman',
    'Panamera'
  ],
  'Saab' => [
    '9-2X',
    '9-3',
    '9-4x',
    '9-5',
    '9-7x',
    '900',
    '9000'
  ],
  'Saturn' => [
    'Astra',
    'Aura',
    'ION',
    'L100',
    'L200',
    'L300',
    'LS',
    'LW1',
    'LW2',
    'LW200',
    'LW300',
    'Outlook',
    'Relay',
    'SC1',
    'SC2',
    'SW1',
    'SW2',
    'Vue'
  ],
  'Scion' => [
    'FRS',
    'iQ',
    'tC',
    'xA',
    'xB',
    'xD'
  ],
  'Smart' => [
    'fortwo'
  ],
  'Subaru' => [
    'Baja',
    'Brat',
    'BRZ',
    'Forester',
    'Impreza',
    'Impreza WRX',
    'Justy',
    'L Series',
    'Legacy',
    'Loyal',
    'Outback',
    'SVX',
    'Tribeca',
    'XT'
  ],
  'Suzuki' => [
    'Aerio',
    'Equator',
    'Esteem',
    'Forenza',
    'Grand Vitara',
    'Kizashi',
    'Reno',
    'Samurai',
    'Sidekick',
    'Swift',
    'SX4',
    'Verona',
    'Vitara',
    'X-90',
    'XL-7'
  ],
  'Toyota' => [
    '4Runner',
    'Avalon',
    'Camry',
    'Celica',
    'Corolla',
    'Corona',
    'Cressida',
    'Echo',
    'FJ Cruiser',
    'Highlander',
    'Landcruiser',
    'Matrix',
    'MR2',
    'MR2 Spyder',
    'Paseo',
    'Pickup',
    'Previa',
    'Prius',
    'RAV4',
    'Sequoia',
    'Sienna',
    'Solara',
    'Starlet',
    'Supra',
    'T100',
    'Tacoma',
    'Tercel',
    'Tundra',
    'Van',
    'Venza',
    'Yaris'
  ],
  'Volkswagon' => [
    'Beetle',
    'Cabrio',
    'Cabriolet',
    'CC',
    'Corrado',
    'Dasher',
    'Eos',
    'Eurovan',
    'Fox',
    'GLI',
    'Golf',
    'Golf R',
    'GTI',
    'Jetta',
    'Passat',
    'Phaeton',
    'Pickup',
    'Quantam',
    'R32',
    'Rabbit',
    'Routan',
    'Scirocco',
    'Tiguan',
    'Touareg',
    'Vanagon'
  ],
  'Volvo' => [
    '240',
    '260',
    '740',
    '760',
    '780',
    '850',
    '940',
    '960',
    'C30',
    'C70',
    'S40',
    'S60',
    'S70',
    'S80',
    'S90',
    'V40',
    'V50',
    'V70',
    'V90',
    'XC60',
    'XC70',
    'XC90'
  ]
}

CheckVin = {
  :weights => [ 8, 7, 6, 5, 4, 3, 2, 10, 0, 9, 8, 7, 6, 5, 4, 3, 2 ],
  :char_trans => {
    'A' => 1, 'B' => 2, 'C' => 3, 'D' => 4, 'E' => 5, 'F' => 6,   'G' => 7, 'H' => 8,   'I' => nil,
    'J' => 1, 'K' => 2, 'L' => 3, 'M' => 4, 'N' => 5, 'O' => nil, 'P' => 7, 'Q' => nil, 'R' => 9,
              'S' => 2, 'T' => 3, 'U' => 4, 'V' => 5, 'W' => 6,   'X' => 7, 'Y' => 8,   'Z' => 9,
    '1' => 1, '2' => 2, '3' => 3, '4' => 4, '5' => 5, '6' => 6,   '7' => 7, '8' => 8,   '9' => 9,   '0' => 0,
  },
  :misreads => { 'O' => 0, 'Q' => 0, 'I' => 1 },
}
