Make.find_or_create_by_name("Acura")
Make.find_or_create_by_name("Alfa Romeo").update_attributes({ :vin_regex => "^(ZAR).*" }, as: :admin)
Make.find_or_create_by_name("Aston Martin").update_attributes({ :vin_regex => "^(SCF).*" }, as: :admin)
Make.find_or_create_by_name("Audi").update_attributes({ :vin_regex => "^(WAU|93U|TRU).*" }, as: :admin)
Make.find_or_create_by_name("BMW").update_attributes({ :vin_regex => "^(WBA|WBS|4US).*" }, as: :admin)
Make.find_or_create_by_name("Bentley")
Make.find_or_create_by_name("Buick").update_attributes({ :vin_regex => "^(2G4|1G4).*" }, as: :admin)
Make.find_or_create_by_name("CODA")
Make.find_or_create_by_name("Cadillac").update_attributes({ :vin_regex => "^(1G6).*" }, as: :admin)
Make.find_or_create_by_name("Chevrolet").update_attributes({ :vin_regex => "^(8AG|9BG|2G1|8GG|MMM|1GC|1G1).*" }, as: :admin)
Make.find_or_create_by_name("Chrysler").update_attributes({ :vin_regex => "^(1C3|2C3).*" }, as: :admin)
Make.find_or_create_by_name("Daewoo").update_attributes({ :vin_regex => "^(KL).*" }, as: :admin)
Make.find_or_create_by_name("Daihatsu")
Make.find_or_create_by_name("Dodge").update_attributes({ :vin_regex => "^(1D3|2D3|3D3).*" }, as: :admin)
Make.find_or_create_by_name("Eagle")
Make.find_or_create_by_name("FIAT").update_attributes({ :vin_regex => "^(ZFA|8AP|9BD|ZFC).*" }, as: :admin)
Make.find_or_create_by_name("Ferrari").update_attributes({ :vin_regex => "^(ZFF|ZDF).*" }, as: :admin)
Make.find_or_create_by_name("Ford").update_attributes({ :vin_regex => "^(MNB|PE1|SFA|TW2|UNI|VS6|WF0|WF1|XLC|Y4F|1F1|1F6|1F7|1FA|1FB|1FC|1FD|1FM|1FT|1L1|1LJ|1LN|1ME|1MH|1YV|1ZV|2FA|2FD|2FM|2FT|2ME|2MH|2MR|3FA|3FD|3FT|3MA|3FN|3FR|4F2|4F4|4M2|5L1|5LM|5LT|6FP|8AF|9BF|8XD).*" }, as: :admin)
Make.find_or_create_by_name("GMC").update_attributes({ :vin_regex => "^(1GT|2G|3G|1G|6G1|6H8).*" }, as: :admin)
Make.find_or_create_by_name("Geo")
Make.find_or_create_by_name("HUMMER")
Make.find_or_create_by_name("Honda").update_attributes({ :vin_regex => "^(JHG|JHL|JHM|93H|2HG|2HK|MHR|3H|MA7|MRH|SHS|1H|5F).*" }, as: :admin)
Make.find_or_create_by_name("Hyundai").update_attributes({ :vin_regex => "^(KM8|KMH|MAL|2HM|5NP).*" }, as: :admin)
Make.find_or_create_by_name("Infiniti")
Make.find_or_create_by_name("Isuzu").update_attributes({ :vin_regex => "^(JA|LZE|MP1|MPA).*" }, as: :admin)
Make.find_or_create_by_name("Jaguar").update_attributes({ :vin_regex => "^(SAJ).*" }, as: :admin)
Make.find_or_create_by_name("Jeep").update_attributes({ :vin_regex => "^(1J4).*" }, as: :admin)
Make.find_or_create_by_name("Kia").update_attributes({ :vin_regex => "^(KNA|KNB|KNC).*" }, as: :admin)
Make.find_or_create_by_name("Lamborghini").update_attributes({ :vin_regex => "^(ZHW).*" }, as: :admin)
Make.find_or_create_by_name("Land Rover").update_attributes({ :vin_regex => "^(SAL).*" }, as: :admin)
Make.find_or_create_by_name("Lexus")
Make.find_or_create_by_name("Lincoln").update_attributes({ :vin_regex => "^(5L|1L).*" }, as: :admin)
Make.find_or_create_by_name("Lotus").update_attributes({ :vin_regex => "^(SCC).*" }, as: :admin)
Make.find_or_create_by_name("MINI").update_attributes({ :vin_regex => "^(WMW).*" }, as: :admin)
Make.find_or_create_by_name("Maserati").update_attributes({ :vin_regex => "^(ZAM).*" }, as: :admin)
Make.find_or_create_by_name("Maybach")
Make.find_or_create_by_name("Mazda").update_attributes({ :vin_regex => "^(JM|PE3|MM8|4F|1YV).*" }, as: :admin)
Make.find_or_create_by_name("McLaren").update_attributes({ :vin_regex => "^(WDD).*" }, as: :admin)
Make.find_or_create_by_name("Mercedes-Benz").update_attributes({ :vin_regex => "^(WDB|9BM|NLE).*" }, as: :admin)
Make.find_or_create_by_name("Mercury").update_attributes({ :vin_regex => "^(2M|4M|1ME).*" }, as: :admin)
Make.find_or_create_by_name("Mitsubishi").update_attributes({ :vin_regex => "^(JA3|XMC|6MM|MMB|MMT).*" }, as: :admin)
Make.find_or_create_by_name("Nissan").update_attributes({ :vin_regex => "^(JN|3N|6F4|VSK|MNT|SJN|1N|5N1).*" }, as: :admin)
Make.find_or_create_by_name("Oldsmobile").update_attributes({ :vin_regex => "^(2G3|1G3).*" }, as: :admin)
Make.find_or_create_by_name("Panoz")
Make.find_or_create_by_name("Plymouth").update_attributes({ :vin_regex => "^(2P3|3P3|1P3).*" }, as: :admin)
Make.find_or_create_by_name("Pontiac").update_attributes({ :vin_regex => "^(6G2|2G2|1G2|1GM).*" }, as: :admin)
Make.find_or_create_by_name("Porsche").update_attributes({ :vin_regex => "^(WPO).*" }, as: :admin)
Make.find_or_create_by_name("Ram")
Make.find_or_create_by_name("Rolls-Royce")
Make.find_or_create_by_name("Saab").update_attributes({ :vin_regex => "^(YK1|YS3).*" }, as: :admin)
Make.find_or_create_by_name("Saturn").update_attributes({ :vin_regex => "^(1G8).*" }, as: :admin)
Make.find_or_create_by_name("Scion")
Make.find_or_create_by_name("Smart")
Make.find_or_create_by_name("Subaru").update_attributes({ :vin_regex => "^(4S).*" }, as: :admin)
Make.find_or_create_by_name("Suzuki").update_attributes({ :vin_regex => "^(JS|8AK|MA3|VSE|TSM).*" }, as: :admin)
Make.find_or_create_by_name("Tesla")
Make.find_or_create_by_name("Toyota").update_attributes({ :vin_regex => "^(4T|JT|8AJ|93R|2T|6T1|MR0|LTV|NMT|5T).*" }, as: :admin)
Make.find_or_create_by_name("Volkswagen").update_attributes({ :vin_regex => "^(WVW|8AW|9BW|WV2|WV1|3VW|AAV|VWV|1VW).*" }, as: :admin)
Make.find_or_create_by_name("Volvo").update_attributes({ :vin_regex => "^(4V1|4V2|4V3|4V4|4V5|4V6|4VL|4VM|4VZ|YV3|YV1|YV4|YV2).*" }, as: :admin)
