require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CarYearsController do

  # This should return the minimal set of attributes required to create a valid
  # CarYear. As you add validations to CarYear, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CarYearsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all car_years as @car_years" do
      car_year = CarYear.create! valid_attributes
      get :index, {}, valid_session
      assigns(:car_years).should eq([car_year])
    end
  end

  describe "GET show" do
    it "assigns the requested car_year as @car_year" do
      car_year = CarYear.create! valid_attributes
      get :show, {:id => car_year.to_param}, valid_session
      assigns(:car_year).should eq(car_year)
    end
  end

  describe "GET new" do
    it "assigns a new car_year as @car_year" do
      get :new, {}, valid_session
      assigns(:car_year).should be_a_new(CarYear)
    end
  end

  describe "GET edit" do
    it "assigns the requested car_year as @car_year" do
      car_year = CarYear.create! valid_attributes
      get :edit, {:id => car_year.to_param}, valid_session
      assigns(:car_year).should eq(car_year)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CarYear" do
        expect {
          post :create, {:car_year => valid_attributes}, valid_session
        }.to change(CarYear, :count).by(1)
      end

      it "assigns a newly created car_year as @car_year" do
        post :create, {:car_year => valid_attributes}, valid_session
        assigns(:car_year).should be_a(CarYear)
        assigns(:car_year).should be_persisted
      end

      it "redirects to the created car_year" do
        post :create, {:car_year => valid_attributes}, valid_session
        response.should redirect_to(CarYear.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved car_year as @car_year" do
        # Trigger the behavior that occurs when invalid params are submitted
        CarYear.any_instance.stub(:save).and_return(false)
        post :create, {:car_year => {}}, valid_session
        assigns(:car_year).should be_a_new(CarYear)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        CarYear.any_instance.stub(:save).and_return(false)
        post :create, {:car_year => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested car_year" do
        car_year = CarYear.create! valid_attributes
        # Assuming there are no other car_years in the database, this
        # specifies that the CarYear created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        CarYear.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => car_year.to_param, :car_year => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested car_year as @car_year" do
        car_year = CarYear.create! valid_attributes
        put :update, {:id => car_year.to_param, :car_year => valid_attributes}, valid_session
        assigns(:car_year).should eq(car_year)
      end

      it "redirects to the car_year" do
        car_year = CarYear.create! valid_attributes
        put :update, {:id => car_year.to_param, :car_year => valid_attributes}, valid_session
        response.should redirect_to(car_year)
      end
    end

    describe "with invalid params" do
      it "assigns the car_year as @car_year" do
        car_year = CarYear.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CarYear.any_instance.stub(:save).and_return(false)
        put :update, {:id => car_year.to_param, :car_year => {}}, valid_session
        assigns(:car_year).should eq(car_year)
      end

      it "re-renders the 'edit' template" do
        car_year = CarYear.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CarYear.any_instance.stub(:save).and_return(false)
        put :update, {:id => car_year.to_param, :car_year => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested car_year" do
      car_year = CarYear.create! valid_attributes
      expect {
        delete :destroy, {:id => car_year.to_param}, valid_session
      }.to change(CarYear, :count).by(-1)
    end

    it "redirects to the car_years list" do
      car_year = CarYear.create! valid_attributes
      delete :destroy, {:id => car_year.to_param}, valid_session
      response.should redirect_to(car_years_url)
    end
  end

end
