require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CarTrimsController do

  # This should return the minimal set of attributes required to create a valid
  # CarTrim. As you add validations to CarTrim, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CarTrimsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all car_trims as @car_trims" do
      car_trim = CarTrim.create! valid_attributes
      get :index, {}, valid_session
      assigns(:car_trims).should eq([car_trim])
    end
  end

  describe "GET show" do
    it "assigns the requested car_trim as @car_trim" do
      car_trim = CarTrim.create! valid_attributes
      get :show, {:id => car_trim.to_param}, valid_session
      assigns(:car_trim).should eq(car_trim)
    end
  end

  describe "GET new" do
    it "assigns a new car_trim as @car_trim" do
      get :new, {}, valid_session
      assigns(:car_trim).should be_a_new(CarTrim)
    end
  end

  describe "GET edit" do
    it "assigns the requested car_trim as @car_trim" do
      car_trim = CarTrim.create! valid_attributes
      get :edit, {:id => car_trim.to_param}, valid_session
      assigns(:car_trim).should eq(car_trim)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CarTrim" do
        expect {
          post :create, {:car_trim => valid_attributes}, valid_session
        }.to change(CarTrim, :count).by(1)
      end

      it "assigns a newly created car_trim as @car_trim" do
        post :create, {:car_trim => valid_attributes}, valid_session
        assigns(:car_trim).should be_a(CarTrim)
        assigns(:car_trim).should be_persisted
      end

      it "redirects to the created car_trim" do
        post :create, {:car_trim => valid_attributes}, valid_session
        response.should redirect_to(CarTrim.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved car_trim as @car_trim" do
        # Trigger the behavior that occurs when invalid params are submitted
        CarTrim.any_instance.stub(:save).and_return(false)
        post :create, {:car_trim => {}}, valid_session
        assigns(:car_trim).should be_a_new(CarTrim)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        CarTrim.any_instance.stub(:save).and_return(false)
        post :create, {:car_trim => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested car_trim" do
        car_trim = CarTrim.create! valid_attributes
        # Assuming there are no other car_trims in the database, this
        # specifies that the CarTrim created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        CarTrim.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => car_trim.to_param, :car_trim => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested car_trim as @car_trim" do
        car_trim = CarTrim.create! valid_attributes
        put :update, {:id => car_trim.to_param, :car_trim => valid_attributes}, valid_session
        assigns(:car_trim).should eq(car_trim)
      end

      it "redirects to the car_trim" do
        car_trim = CarTrim.create! valid_attributes
        put :update, {:id => car_trim.to_param, :car_trim => valid_attributes}, valid_session
        response.should redirect_to(car_trim)
      end
    end

    describe "with invalid params" do
      it "assigns the car_trim as @car_trim" do
        car_trim = CarTrim.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CarTrim.any_instance.stub(:save).and_return(false)
        put :update, {:id => car_trim.to_param, :car_trim => {}}, valid_session
        assigns(:car_trim).should eq(car_trim)
      end

      it "re-renders the 'edit' template" do
        car_trim = CarTrim.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CarTrim.any_instance.stub(:save).and_return(false)
        put :update, {:id => car_trim.to_param, :car_trim => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested car_trim" do
      car_trim = CarTrim.create! valid_attributes
      expect {
        delete :destroy, {:id => car_trim.to_param}, valid_session
      }.to change(CarTrim, :count).by(-1)
    end

    it "redirects to the car_trims list" do
      car_trim = CarTrim.create! valid_attributes
      delete :destroy, {:id => car_trim.to_param}, valid_session
      response.should redirect_to(car_trims_url)
    end
  end

end
